### ISSUE TITLE
Surfacing updates outside of Twitch

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/alveusgg#330]
> Hey, it's knayte/Nate,
> 
> Ok, as a new user, I'm going to use myself as a case study...and in doing so, I'll probably make myself sound like a boomer.
> 
> So, up until a month or two ago I had never been on:
> 
> Twitch
> Twitter
> Instagram
> Discord
> 
> I literally had to make accounts on all of them to be able to keep track of what's going on with Alveus/Maya, or just to get the "full experience".  I really don't GAF about social media, and Twitch just didn't have anything to offer(until I learned otherwise).  So yeah, I was watching on YouTube...and when I wanted to dive deeper, it was a bit of a long haul.
> FWIW, I'm on a homebuilt Debian machine, and have a better-than-average tech background (not tech illiterate)...I just literally don't give a fuck about every platform that comes out.
> 
> And...here I am, now discussing this on another platform. :)
> 
> Prior to getting on Twitch, I felt compelled to donate...however, due to lack of a URL on the videos, I had to GOOGLE Alveus to find the site.  (it's better now...but just telling the story).  So, from the website, I ordered something off the wishlist.  On that PO box day, I mentioned in the note that I was watching on YouTube...and Maya seemed shocked that I had found the wishlist off of YouTube?  I was really confused how that was the case.  On the most recent PO day, a bunch of VOD watchers started commenting...and again Maya was weirdly shocked that there were so many?
> 
> Those are the kinds of things that make me think that there is WAY too much tunnel vision with Twitch.  I think it's perfectly fine if Twitch is "the core", and everything branches from it...I don't think there's any particular reason to do the streams on YouTube.  But I think the assumption that everyone uses Twitch, or wants to...is a poor one.  And it SUCKS getting on there for the first time...none of those ! commands are obvious to a new user. Nor is the need for the emote extensions...which leaves chat looking cryptic for anyone that just walks in (not that it's much better afterwards)
> 
> As per usual, there are a lot of ways to skin a cat.  But, I'm not convinced focusing on Twitch enhancements is the key.  I think "the net" gets cast much wider if there is some form of media that can be disseminated to the platforms outside of Twitch, that negate the need for a viewer to follow half a dozen different platforms.  Eg, a short (60sec) weekly update video...not to burden anyone with more production, but Maya seems pretty good at doing short, off-the-cuff, statements...and it wouldn't require anything more than a cell phone and a bit of trimming?  Twitch can still be the best experience...but the key info still needs to be accessible externally, quickly and easily.
> 
> I'm not opposed to in-stream enhancements...I just don't think they are the be-all-end-all.

> Or, ya know, a couple paragraphs in a weekly newsletter that gets emailed out.  I currently get newsletters from several YouTube channels and non-profits.  
> 
> I don't know why some people are starting to turn their noses up at email...but, the "young demographic" may be another misguided fixation?

_Originally posted by @Masternater in https://github.com/alveusgg/alveusgg/issues/329#issuecomment-1637113221_

**Comment by MattIPv4** [comment]
I will note that we now have alveus.gg/updates, which shares key announcements from Alveus (e.g. summer camp coming soon, and the merch drop), as well as notifications for each stream that happens.

The Alveus team themselves appear to use Twitter primarily as the platform where updates are disseminated, and YouTube is used primarily for educational, produced content.

What would you expect to see in weekly update videos, or in a newsletter? There's not always something major happening at Alveus? But perhaps I'm misunderstanding the level of detail you expect?

**Comment by pjeweb** [comment]
I do like the general idea of a news digest. I felt similar-ish to nate before i delved deeper into alveus. Not sure about the media (newsletter, blog, update videos, social media posts) and frequency (weekly, bi-weekly, monthly).

Other than upcoming things (events, streams, plans, new ambassadors), it could also contain a few "good" clips or content of the past period, maybe even small things like: "Pasture got mineral blocks" or a mic upgrade or whatever.

The biggest question is, what is feasible, what needs Alveus (staff or team) and what can be community driven. Announcements/schedule should be fairly easy, since there is a workflow for social media already, but further content or write-ups would be additional work. I am not sure how we can help there really. We could offer a way to collect content and/or publish that, but content production would be on the Alveus team.

I do like when Connor goes through the clips. Maybe we can set up something like https://smashscene.com/qtcinderella and include the top-voted clips, but we also have a highlights yt channel already?!

**Comment by Masternater** [comment]
I don't think it needs much detail at all, that's why I'm saying 60 seconds or so.  Just, "this, this and this is happening this week...this is upcoming. See ya, bye".  And then blanket all the platforms with that unified message.  

What I've seen though, is that the monthly schedule seems to end up as a case of "the best laid battle plans, don't survive first contact with the enemy"...it changes as things progress throughout the month (as it should be able to for the sake of the Alveus team)...but then all the subsequent "updates" have to be dug out of various sources.  Plus, what has really been poor promotion of fundraisers, can be pretty detrimental.   The Wolf Conservation Center was pretty thin on info, until the week before...and it was one or two days prior, before a time was even mentioned...AND that info was buried within a multi-hour stream.  Now with Summer Camp, I don't think any of the viewers had much idea of the "format" until last Friday...though, I guess that is a week notice....but same situation: info buried in a multi hour stream.  If a donor needs to carve out a 3 hour window in their day...speaking from experience, it's helpful to have a good bit of notice when that needs to be.

I think to pick any particular platform as the "primary" means of disseminating info is a horrible idea.  There are 8ish billion people on the planet...it's likely that many use at least one of the platforms, but the number that use ALL the platforms is going to be much smaller.  There are absolutely people that never want to use Twitter...or Twitch....or Instagram.

I know there is a temptation to try to apply a technological solution, and there are improvements that could be made...but I think this is more of a process/strategy/perspective issue.  It's not a very flattering way to say it, but as a non-profit, they are basically begging for money...so the goal should be to cast the net as wide as possible.  But right now, it feels like you have to puzzle-piece the info together from multiple sources...and potential viewers are getting cut out of things.

**Comment by Masternater** [comment]
In addition...the viewership on the streams, gets dwarfed by the views on the shorter YouTube clips.

**Comment by MattIPv4** [comment]
> What I've seen though, is that the monthly schedule seems to end up as a case of "the best laid battle plans, don't survive first contact with the enemy"...it changes as things progress throughout the month (as it should be able to for the sake of the Alveus team)...but then all the subsequent "updates" have to be dug out of various sources. Plus, what has really been poor promotion of fundraisers, can be pretty detrimental. The Wolf Conservation Center was pretty thin on info, until the week before...and it was one or two days prior, before a time was even mentioned...AND that info was buried within a multi-hour stream. Now with Summer Camp, I don't think any of the viewers had much idea of the "format" until last Friday...though, I guess that is a week notice....but same situation: info buried in a multi hour stream. If a donor needs to carve out a 3 hour window in their day...speaking from experience, it's helpful to have a good bit of notice when that needs to be.

This is really what we're trying to solve with alveus.gg/updates, a central place that isn't social media that will have all the key updates for upcoming events etc., with an up-to-date schedule of what's coming soon that's known.

> I know there is a temptation to try to apply a technological solution, and there are improvements that could be made...but I think this is more of a process/strategy/perspective issue.

If that's the case, then, unfortunately, this isn't really the place to be raising it, we can't action that. We're not Alveus, we're community members that build a website and Twitch extension.

**Comment by Masternater** [comment]
> We're not Alveus

You've got their ear more than I do. 
 
My options are: Trying to squeeze a couple lines of text, into a chat being spammed with a bunch of emotes, hoping that someone reads it. 

I'm seeing money being left on the table.

**Comment by MattIPv4** [comment]
I hear you on that, I raised it with the Alveus team and we had a chat about the thoughts you laid out here.

Alveus' primary platform is Twitch. This is an active choice by Alveus to use Twitch as their primary platform, as that is where the demographic and audience they want to target is located. Alveus doesn't want to target all "8ish billion people on the planet", they are trying to target a younger audience that is active on social media, an audience that is less likely to be exposed to other forms of conservation messaging. I don't think that approach to their mission is "misguided", it is an active choice to target a specific audience that otherwise might not learn about conservation, on the platforms that demographic is likely to be found on. If someone isn't active on social media at all, they are unfortunately unlikely to be the audience that Alveus is actively trying to target -- of course, that doesn't mean they can't consume Alveus' content and wouldn't benefit from the education still, but the content and communication from Alveus won't be catered to them.

The YouTube channel is a secondary platform for Alveus, where they publish curated educational videos about conservation. This again is primarily done to target a similar demographic/audience, but allowing the conservation messaging to reach a wider audience in a more condensed format. Alveus also publishes short-form content to a few platforms, all with a similar intention of spreading the messaging and aiming to convert folks over to Twitch, the primary platform for Alveus. All the YouTube videos produced by Alveus should have links in the description to take folks to the Twitch stream if they want to see more, or to the website or the other social media accounts that Alveus have if they want to follow for updates. YouTube itself as a platform is not one that is conducive to sharing real-time updates, hence all the videos have those links to Alveus' social accounts so folks can follow there.

On the subject of sharing updates and social accounts, Alveus most definitely doesn't expect that everyone follows Alveus on every platform. Alveus' primary platform is Twitch, that's where the main content is, but updates about upcoming events and so on are shared on their other social accounts as well, with a unified message. With the example of Summer Camp, it has been discussed informally on streams quite a bit recently, and then was formally announced across all of Alveus' social accounts and the website on Friday. Folks don't need to be watching the stream 24/7 to get that information, nor do they need to follow on every platform, the same update was shared to all of them.

As you note, plans change, and that's generally why Alveus avoids announcing things until they are set in stone. Using Summer Camp as an example again, while it had been discussed on streams before Friday informally, it was only announced on Alveus' social channels once the team was comfortable the plans were finalised enough that they weren't going to change drastically, and with timing such that it'd give folks time to "prepare" for the stream happening in a week, without being announced so far out in advance that folks would start to forget about it and the hype lose traction. (I should also note here that the Wolf Conservation Center stream was not an Alveus stream, hence you likely didn't see it promoted anywhere by Alveus. That was part of Maya's personal Conservation Uncharted series.)

That all being said, we now have the website for updates as well to cater to folks that might not be as active on social media, though the content itself will still primarily be on Twitch as that's the audience that Alveus wants to target. There is definitely merit to your suggestion of looking at email as another channel for folks to get updates through, for upcoming events etc. While I don't think a weekly newsletter format would work (it'd require human effort to curate it each week, and require enough happening each week to make the newsletter worthwhile), I definitely think it'd be worth us looking at allowing the website update notifications to be sent via email, like we do push notifications, and maybe even the option of getting a weekly digest of those notifications, instead of them being sent real-time.
