### ISSUE TITLE
List recent streams/vods

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#331]
Consider adding a system to mark vod timestamps and/or highlights and list them on the site and with a chat command (!recent). Maybe add tags to vods so we can group them by show (keeper talk, projects with Connor, etc).

Speak with the Alveus team about the current workflow and how to improve it.

~~How to handle vods being auto-deleted.~~ => highlights prevent them from being deleted

How does this relate to twitch native features (markers, highlights, schedule).

**Comment by pjeweb** [comment]
We dont really need this anymore since the stream -> highlight -> youtube process has been set up.

**Comment by pjeweb** [comment]
Still relevant. Maybe we can use https://jakemiki.github.io/twitch-clip-queue/

**Comment by MattIPv4** [comment]
I wonder if a better way to approach this would be to tie it into the updates system? Maybe instead of manually sending an update for things happening on the livestream, there's a command/UI to add an "event" that is happening, which'd then feed the data for this but also trigger an update to be sent?

**Comment by MattIPv4** [comment]
Closing in favour of #636
