### ISSUE TITLE
[Bug]: Small gap in socials footer below video

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#358]
### What is the current behavior?

There is a small gap below the video in the socials footer with viewport widths around 850px

<img width="930" alt="gap" src="https://github.com/alveusgg/alveusgg/assets/684458/325a3817-ec65-4578-bb18-ae08069861a6">

### What is the expected behavior?

No gap

### Steps to reproduce

Visit site, scroll down, limit viewport to 850px width (using dev tools or window size)

### Browser specs

any

**Comment by tomoyukiy** [comment]
Since the video element is smaller than the social app element, there seems to be a gap under the video element.
The default height of the video element is 305px, but by specifying the "-mt-10" class, the height was 265px.
After changing the value of margin-top the gap is gone. 
PR: #363 

![alveusgg_issues_358](https://github.com/alveusgg/alveusgg/assets/38880175/d131dbf1-9cab-4f9e-8004-614ddb70c925)

<img width="849" alt="alveusgg_issues_358_2" src="https://github.com/alveusgg/alveusgg/assets/38880175/1ff8cd95-5b89-441f-a20b-6b93eea1ddc3">
