### ISSUE TITLE
[Idea]: Is it possible to open the whatsmybrowser link in bug report template in new tab

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#359]
### Describe your idea / enhancement

If possible the "What's my browser" link should open in a new window:
https://github.com/alveusgg/alveusgg/blob/c8e869db1e71138472d5ede7cc2123824690429c/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L32

I'm not sure if you can use markdown syntax or something similar in the [github form syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema).

### How would this idea / enhancement be beneficial?

Does not interrupt the issue writing process and/or does not confuse because the issue text seems to be lost.

**Comment by nslee333** [comment]
I can look into this.

**Comment by nslee333** [comment]
I don't think this is possible, 

GH flavored .md doesn't support it according to [stack overflow](https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank), and [this issue](https://github.com/mojombo/github-flavored-markdown/issues/28). There dosen't seem to be any options for links in the gh form syntax either unfortunately. It's weird because it feels like something they should have.

**Comment by pjeweb** [comment]
> I don't think this is possible

ty for checking!
