### ISSUE TITLE
[Idea]: Reduce the container width to 1200px

### ISSUE THREAD

**Issue by sougataghar477** [alveusgg/alveusgg#394]
### Describe your idea / enhancement

Present Container Width i,e,1536px
![image](https://github.com/alveusgg/alveusgg/assets/50982886/e87caf6a-b50c-43cb-b19c-483df024c0c7)
Suggested Container Width of 1200px
![image](https://github.com/alveusgg/alveusgg/assets/50982886/64b6ea60-dbed-47b3-bc60-f2e6488c1999)

### How would this idea / enhancement be beneficial?

I just feel reducing the container width would make it better looking since things are in the center which human eyes prefer to look at !

**Comment by MattIPv4** [comment]
👋 While I'm not completely against this idea, this would be a _major_ change to the site that would need us to rethink the design of most of the pages at desktop viewports, as we suddenyl would have a lot less room to play with for more complex layouts.

For example, we would likely need to completely rethink how the ambassador pages work, as with as 1200px container, we have a lot less space to work with in the first section:

![image](https://github.com/alveusgg/alveusgg/assets/12371363/0fed3f42-bece-44b7-8521-12b28a391b9b)

I do see how this would benefit some of our pages, and sections within them, such as the homepage hero, but I'm not sure globally changing the container widths in tailwind would benefit everything. Beyond personal perference around it centering the content more, is there any specific problem that this change would solve? Are there any specific benefits?

**Comment by sougataghar477** [comment]
I don't think this would solve anything else other than centering and the ambassador as well other page looks fine 
![image](https://github.com/alveusgg/alveusgg/assets/50982886/91006a6d-98cf-46b1-9bfc-235759866766)

**Comment by sougataghar477** [comment]
I just think this change has way more positives than negatives .

**Comment by MattIPv4** [comment]
I'm not sure that I agree this has way more positives than negatives -- it has a single positive, centering the content more, but the negatives are that it is going to break the layout of multiple pages and require them to be reworked:

The individual ambassador pages become far too crowded and look odd, so would have to be redesigned:

![image](https://github.com/alveusgg/alveusgg/assets/12371363/a9c1ffa5-471f-4c76-865c-813ff196d4f6)

Similarly, the about page becomes incredibly crowded so we'd need to rethink the layout here with the content and video:

![image](https://github.com/alveusgg/alveusgg/assets/12371363/8d18238c-a2bd-4f1d-81b0-483056f5b8cf)

On quite a few of the content-heavy pages, we have a very large amount of space left unused now, which I suppose could be seen as a benefit in that the content is narrower which some find easier to read, but also wastes a lot of space on the page that we could be using:

![image](https://github.com/alveusgg/alveusgg/assets/12371363/194a874d-f9a9-4af9-a371-5923d5e87071)

All-in-all, the only benefit this seems to have is just that the content becomes slightly more centered at viewports around 1920px (larger viewports will already have the content more centered as 1536px is the largest breakpoint, and anything smaller will still use most of the viewport anyway). But at the same time, it causes layout issues on multiple pages that will need us to rethink how those pages are designed, and leaves a lot of space on pages that is unused.

If there was a strong argument for a design perspective, or an accessibility perspective, I'd be more inclined to invest in solving this, but currently, it just seems to be a suggestion based on personal preference for smaller content widths, and I'm not sure that is reason to put work into changing site design for.

**Comment by sougataghar477** [comment]
I really dont see an isssue in the about pages, think it looks better centered than floating to the sides and as for the ambassador I can use ternary operator to make that page stick to the original size

**Comment by MattIPv4** [comment]
I've chewed on this over the last day, and I think my position on this is that I'm against making this change across the whole site, but I'm open to doing this on specific pages if there is a strong concern with layouts on them. Doing this across all pages just feels like making a change for the sake of making a change, and applying personal preference, rather than addressing a specific design issue.

@pjeweb open to your thoughts on this though?

**Comment by sougataghar477** [comment]
what about just the hero section?

**Comment by pjeweb** [comment]
So for the hero section on the home page i think it would be good to add some more padding. It looks out of line with the logo and content imho. The video could maybe also be a tad smaller.
<img src="https://github.com/alveusgg/alveusgg/assets/684458/6803017c-550e-4990-8f63-72ccd47f752f" width="200" alt="">

For the ambassador page I'm not sure what you did there, matt, but I think it looks pretty decent if you change the header width also like you did on the about page or as proposed for the home page. The concern with leaving lots of unused space would remain though. I made a PR #396 so we can look at the same version: https://alveusgg-website-git-pjeweb-container-w-alveus.vercel.app/

For the About Alveus page I think this should probably be fine tuned regardless of this Issue, because it looks that crowded on medium desktop viewports. We might need to wrap the image below earlier and/or change the ratio.

All in all I personally slightly prefer the smaller container width, but I agree this would need some tuning on most pages and I don't see a real need to change anything.

**Comment by MattIPv4** [comment]
👀 Definitely agree that we can add a bit more padding to the homepage hero so that it looks more visually aligned with the main body of the logo (I imagine it is currently aligned to the last pixel of the swoosh).

I can also get a quick PR in to fix the about page, looks like I got a breakpoint wrong on that for sure. Still not a fan of constraining the width there more by default though, I think the layout we have definitely benefits from the wider container, given the written content is already constrained to ~50% the width.

My concern with the ambassador pages still feels like a concern to me, they feel very unbalanced with this reduced container width -- the ambassador photo still takes up half of the page, but now the information is squashed into a much smaller area with a load of whitespace left to the side, and that looks really visually odd to me.

**Comment by pjeweb** [comment]
Yeah I'd be happy fixing some things here and there and keep the wider width in general.
