### ISSUE TITLE
[Bug]: Users getting stuck with active session connected to deleted twitch account

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#450]
### What is the current behavior?

Users with an existing session that delete their twitch account (or get banned) can't log out and log in with their new account.

### What is the expected behavior?

When the twitch account is deleted and a user returns, they should be logged out and possibly the account be marked as deleted.

### Steps to reproduce

- Login with account A
- Delete twitch user connected to account A (or get it banned)
- Without deleting cookies return to the site

### Browser specs

n/a

### Anything else?

Very edge case. Probably easier to send them a link to delete cookies for that case. "Try another browser" apparently did not work in the one case, deleting the user in our DB did.

**Comment by bl4nkfce** [comment]
@pjeweb @MattIPv4 
I had a quick look at this issue and am not sure if I can reproduce it correctly but I noticed that we're only validating tokens in the `adminTwitchRouter` router (maybe I'm missing something).

The Twitch [docs](https://dev.twitch.tv/docs/authentication/validate-tokens/) states that we should validate them hourly.

next-auth has a guide related to [token rotation](https://authjs.dev/guides/refresh-token-rotation#database-strategy) with database strategy.

We already have a [function](https://github.com/ACA30/alveusgg/blob/ed374d5d8aa48b81f0f37e0537dcd8b8ad5f1e0a/apps/website/src/server/utils/oauth2.ts#L26) that calls the validation endpoint, but it checks the incorrect status code (should be 401 instead of 403).

I think we can export this function, follow this guide and update our db accordingly, based on the response form the validation endpoint.
This would _probably_ resolve this issue as well as automatically log-out users that disconnect the app in the Twitch profile settings (Twitch automatically invalidates the token) which currently does not happen.

**Comment by pjeweb** [comment]
Sorry for not responding earlier. Validating the tokens with twitch regularly on session validation makes sense!
Would you want to help implement this? Would be happy to accept the PR.

**Comment by bl4nkfce** [comment]
Yeah I can take a look at it
